name: deploy marimo

permissions: read-all

env:
  UV_SYSTEM_PYTHON: 1

on:
  push:
    branches:
      - main
jobs:
  deploy_app:
    name: Deploy app
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        folder:
          - "sample"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt

      - name: 📄 Export notebook
        run: |
          marimo export html-wasm marimo/${{ matrix.folder }}/app.py -o public --mode edit

      - name: Publish app
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ./marimo/${{ matrix.folder }}