name: Release

on:
  push:
    tags: ["*"]

permissions: read-all

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: release

    # Mandatory permission for trusted publishing to PyPi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv pip install setuptools build

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
